name: Build&gh-pages

on:
  workflow_dispatch: 
  push:
    branches:
      - main  # 触发条件，推送到 main 分支时

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install  # 安装依赖

      - name: Build VitePress
        run: npm run build  # 执行构建命令，确保 package.json 中定义了 build 脚本

      # 4. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./.vitepress/dist  # 构建目录
          publish_branch: gh-pages  # 发布到 gh-pages 分支
          user_name: 'github-actions'  # 提交者名称
          user_email: 'github-actions@github.com'  # 提交者邮箱

      # 配置 s3
      - name: Configure AWS credentials for Profile Tebi
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.TEBI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEBI_SECRET_ACCESS_KEY }}
          aws-region: 'auto'

      # 4. 同步到 Tebi 的 S3 存储桶
      - name: Sync to Tebi S3 Bucket
        run: |
          aws s3 sync ./.vitepress/dist s3://param.us.kg --endpoint-url https://s3.tebi.io --profile tebi
