name: Deploy VitePress

on:
  push:
    branches:
      - main  # 触发条件，推送到 main 分支时

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 使用你项目所需的 Node.js 版本

      - name: Install dependencies
        run: npm install  # 安装依赖

      - name: Build VitePress
        run: npm run build  # 执行构建命令，确保 package.json 中定义了 build 脚本

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.RAN_ACTIONS_TOKEN }}  # 自动生成的 GitHub Token
          publish_dir: .vitepress/dist  # VitePress 构建输出的目录（默认为 ./dist）
          publish_branch: gh-pages  # 要发布的目标分支
